# version: '3.8'

services:
  coyote:
    build: .
    image: ghcr.io/captaininfo/coyote:latest
    container_name: coyote_app
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    #depends_on:  []     
    environment:
      - NEO4J_URI=bolt://database:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
    networks:
      - coyote_genai_net
    restart: unless-stopped
    
networks:
  coyote_genai_net:
    external: true
    name: coyote_genai_net

  #neo4j:
    #image: neo4j:5.11
    #container_name: neo4j_db
    #ports:
      #- "7474:7474"  # Neo4j Browser
      #- "7687:7687"  # Bolt protocol
    #volumes:
      #- neo4j_data:/data
    #environment:
      #- NEO4J_AUTH=none  # Login creds disbled for beta testing
      #- NEO4J_PLUGINS=["apoc"]
      #- NEO4J_dbms_security_procedures_unrestricted=apoc.*,db.schema.*
      #- NEO4J_dbms_security_procedures_allowlist=apoc.*,db.schema.*
    #restart: unless-stopped

  #llm_service:
    #image: ollama/ollama:0.4.6
    #container_name: coyote_llm
    #volumes:
    #- ./ollama/models:/root/.ollama           # persistent GGUF cache
    #ports:
    #- "11434:11434"
    #environment:
    #- OLLAMA_ORIGINS=*
    #restart: unless-stopped

  #agent_worker:
    #build: ./agent_worker
    #depends_on:
      #- neo4j
      #- llm_service
    #environment:
      #- LLM_ENDPOINT=http://llm_service:11434
      #- NEO4J_URI=bolt://neo4j_db:7687
    #ports:
      #- "8000:8000" 

#volumes:
  #neo4j_data:
