name: "🐛 Bug report"
description: "Something isn't working"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for helping make Coyote better!
        Please fill in what you can — required fields are marked **(required)**.

  - type: input
    id: title
    attributes:
      label: Title **(required)**
      description: One short sentence that describes the bug.
      placeholder: "Configure page returns 404"
    validations:
      required: true

  - type: textarea
    id: description           
    attributes:
      label: Description **(required)**
      description: Describe the bug.
      placeholder: |
        The Coyote container appears to start up fine...
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: Bullet-list the steps.
      placeholder: |
        1. Open terminal  
        2. Run `docker compose up -d`  
        3. …
  
  - type: dropdown
    id: os
    attributes:
      label: Operating system **(required)**
      options: ["Linux","macOS","Windows","Other"]
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options: ["Firefox","Chrome","Safari","Edge","Other"]

  - type: input
    id: docker_version
    attributes:
      label: Docker version
      description: "In CLI, run 'docker --version' and 'docker compose version'"
      placeholder: "Docker 25.0.3"

  - type: input
    id: docker_compose_version
    attributes:
      label: Docker Compose version
      description: "In CLI, run 'docker --version' and 'docker compose version'"
      placeholder: "Compose v2.27.0"

  - type: textarea
    id: logs
    attributes:
      label: Paste or attach `coyote_server.log`
      description: Drag-and-drop if large. File path: `coyote/data/logs/coyote_server.log`

  - type: checkboxes
    id: willing_to_fix
    attributes:
      label: Willing to work on a fix?
      options:
        - label: I am willing to submit a PR
