name: "🐛 Bug report"
description: "Something isn't working"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for helping make Coyote better!
        Please fill in what you can — required fields are marked **(required)**.

  - type: input
    id: title
    attributes:
      label: title **(required)**
      description: One short sentence that describes the bug.
      placeholder: "Configure page returns 404"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description **(required)**
      description: Describe the bug.
      placeholder: "The Coyote container appears to start up fine. However, when I try to open the Configure webpage at http://localhost:5000/configure, I get a 404 error."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce 
      description: Bullet list of steps.
      placeholder: |
        1. Open terminal  
        2. Run `docker compose up -d`  
        3. …
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating system **(required)**
      options: [Linux, macOS, Windows, Other]
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Operating system
      options: [Firefox, Chrome, Safari, Edge, Other]
    validations:
      required: false

  - type: input
    id: docker_version
    attributes:
      label: Docker / Compose version
      placeholder: "In CLI, run 'docker --version' and 'docker compose version'"

  - type: textarea
    id: logs
    attributes:
      label: Paste or attach `coyote_server.log`
      description: Drag-and-drop if large. Find the 'coyote_server.log' file in your Coyote directory: coyote/data/logs/coyote_server.log
    validations:
      required: false

  - type: checkboxes
    id: willing
    attributes:
      label: I’d like to fix this bug
      options:
        - label: I’m willing to submit a PR
